# Generated by Django 3.1.4 on 2020-12-14 13:08

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201214_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.FileField(null=True, upload_to=mainapp.models.upload_image_path)),
                ('product_description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('TechnicianId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.techniciandetails')),
            ],
        ),
    ]
