# Generated by Django 3.1.4 on 2020-12-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductTech',
        ),
    ]
