# Generated by Django 3.1.4 on 2020-12-14 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_auto_20201214_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniciandetails',
            name='TechnicianId',
        ),
        migrations.AddField(
            model_name='techniciandetails',
            name='TechnicianId',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
